name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정(UTC)에 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
      - name: Push Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
